# This is a docker-compose file for a 3-tier application consisting of a frontend, backend and database service.
version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
    ports:
      - "${PORT}:${PORT}"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
    command: -p ${DB_PORT}
volumes:
  db:
    driver: local
