# This is a docker-compose file for a 3-tier application consisting of a frontend, backend and database service.
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
    ports:
      - "${PORT}:${PORT}"
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/api

  db:
    build:
      context: .
      dockerfile: Dockerfile.dev.db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
    command: -p ${DB_PORT}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db:
    driver: local
  pgadmin-data:
